paths:
  /alerts/{id}/posts:
    get:
      operationId: listPostsForAlert
      tags:
        - Alerts
        - Posts
      summary: List all posts for an alert
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostResponse'
    post:
      operationId: createPost
      tags:
        - Alerts
        - Posts
      summary: Create a new post against alert
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
      responses:
        '201':
          description: Post created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
  /posts/{postId}:
    put:
      operationId: updatePost
      tags:
        - Posts
      summary: Update an existing post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePostRequest'
      responses:
        '200':
          description: Post updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        '400':
          description: Bad request - invalid content
        '403':
          description: Forbidden - user is not the author of the post
        '404':
          description: Post not found
    delete:
      operationId: deletePost
      tags:
        - Posts
      summary: Delete an existing post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Post deleted successfully
        '403':
          description: Forbidden - user is not authorized to delete this post
        '404':
          description: Post not found
components:
  schemas:
    PostRequest:
      type: object
      example:
        username: "hannah-bannanah"
        content: "I think I saw him yesterday"
      properties:
        username:
          type: string
        content:
          type: string
      required:
        - username
        - content
    PostResponse:
      type: object
      example:
        id: 1
        alertId: 1
        username: "hannah-bannanah"
        content: "I think I saw him yesterday"
        createdAt: "2025-04-17T16:40:27.914Z"
      properties:
        id:
          type: integer
        alertId:
          type: integer
        username:
          type: string
        content:
          type: string
        createdAt:
          type: date
    UpdatePostRequest:
      type: object
      example:
        content: "Updated content for the post"
      properties:
        content:
          type: string
          maxLength: 500
      required:
        - content
