# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: petsignal-be
  
  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Jackson Configuration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  
  # Spring DevTools Configuration
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  # Email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
        test-connection: true

# OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
  show-actuator: false

# AWS Configuration
aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    region: ${AWS_REGION:us-east-1}
    bucket-name: ${AWS_S3_BUCKET_NAME}

# Scheduled jobs configuration
scheduling:
  delete-photos:
    cron: "0 0 3 * * *"
