openapi: 3.1.0
info:
  title: PetSignal API
  description: API for managing pet alerts and notifications
  version: 1.0.0

tags:
  - name: Alerts
    description: Operations about alerts
  - name: Photos
    description: Operations about alert photos
  - name: Users
    description: Operations about users
  - name: Subscriptions
    description: Operations about subscriptions
  - name: Notifications
    description: Operations about notifications

servers:
  - url: http://localhost:8080
    description: Local development server

security:
  - basicAuth: [ ]


paths:
  /alerts:
    $ref: './openapi/alert-openapi.yaml#/paths/~1alerts'
  /alerts/{id}:
    $ref: './openapi/alert-openapi.yaml#/paths/~1alerts~1{id}'
  /alerts/{id}/photos:
    $ref: './openapi/alert-openapi.yaml#/paths/~1alerts~1{id}~1photos'
  /alerts/{id}/photos/{s3ObjectKey}:
    $ref: './openapi/alert-openapi.yaml#/paths/~1alerts~1{id}~1photos~1{s3ObjectKey}'

  /alerts/{id}/posts:
    $ref: './openapi/post-openapi.yaml#/paths/~1alerts~1{id}~1posts'

  /photos/s3:
    $ref: './openapi/s3-photo-openapi.yaml#/paths/~1photos~1s3'

  /users:
    $ref: './openapi/users-openapi.yaml#/paths/~1users'
  /users/{id}:
    $ref: './openapi/users-openapi.yaml#/paths/~1users~1{id}'

  /subscriptions:
    $ref: './openapi/subscriptions-openapi.yaml#/paths/~1subscriptions'
  /subscriptions/{id}:
    $ref: './openapi/subscriptions-openapi.yaml#/paths/~1subscriptions~1{id}'

  /auth/forgot-password:
    $ref: './openapi/auth-openapi.yaml#/paths/~1auth~1forgot-password'
  /auth/verify-reset-token/{token}:
    $ref: './openapi/auth-openapi.yaml#/paths/~1auth~1verify-reset-token~1{token}'
  /auth/reset-password:
    $ref: './openapi/auth-openapi.yaml#/paths/~1auth~1reset-password'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
