services:
  db:
    image: mysql:8.0
    container_name: petsignal-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - petsignal_mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql-files
    ports:
      - '3306:3306'

volumes:
  petsignal_mysql_data:
    driver: local
